### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [mamamarina/grid-template#1]
1)
требования к высоте секции не выполнены.
![image](https://user-images.githubusercontent.com/8464662/99116886-6ff1c000-25fd-11eb-87b6-7f0d9d26d625.png)

**Comment by Alecto** [comment]
2)
использование элементов вне блока
![image](https://user-images.githubusercontent.com/8464662/99117056-bc3d0000-25fd-11eb-920e-36564c741bed.png)

3)
меню так всегда отображается и работает некорректно
![image](https://user-images.githubusercontent.com/8464662/99117128-dd055580-25fd-11eb-8157-9ce1604fef00.png)

**Comment by Alecto** [comment]
4)
цвет не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/99117274-1a69e300-25fe-11eb-9739-341d6825b6bb.png)

**Comment by mamamarina** [comment]
1. Поставила высоту в 1 экран=100vh.
2.Исправила классы.
3.  С адаптивным меню я зашла в тупик. При первом открывании на планшетном и мобильном разрешении оно раскрытое. Если его закрыть-открыть и снова менять разрешение, оно уже нормально устанавливается триггером. Но обновив браузер или запустив заново gulp watch, снова тановится открытым. !important не помог.
4. Цвет placeholder в секции form исправила по макету, заодно и hover по макету сделала. До этого было все по мастер-шаблону.

**Comment by mamamarina** [comment]
Здравствуйте!
Работа над ошибками:
https://github.com/mamamarina/grid-template.git

**Comment by Alecto** [comment]
чудесно.
еще две ссылочки пожалуйста

ср, 18 лист. 2020 о 21:12 Maryna Tuboleva <notifications@github.com> пише:

**Comment by mamamarina** [comment]
https://github.com/mamamarina/grid-template/issues/1

https://github.com/mamamarina/grid-template.git

https://github.com/mamamarina/grid-template/deployments

Вот так?

**Comment by Alecto** [comment]
Нет. Почитайте Критерии защиты проекта

чт, 19 нояб. 2020 г., 9:40 Maryna Tuboleva <notifications@github.com>:

> https://github.com/mamamarina/grid-template/issues/1
>
> https://github.com/mamamarina/grid-template.git
>
> https://github.com/mamamarina/grid-template/deployments
>
> Вот так?
>

**Comment by mamamarina** [comment]
Перечитала. 2 ссылки нужно отправить: на репозиторий и на git hub pages.

https://mamamarina.github.io/grid-template/
https://github.com/mamamarina/grid-template.git

**Comment by Alecto** [comment]
5)
требования к высоте секции не выполнены
![image](https://user-images.githubusercontent.com/8464662/99643264-25d16a00-2a55-11eb-8e3e-443cbbd404db.png)


6)
не соответствует макету
![image](https://user-images.githubusercontent.com/8464662/99643346-3bdf2a80-2a55-11eb-8b7e-4db108732113.png)


7)
?
![image](https://user-images.githubusercontent.com/8464662/99643476-64ffbb00-2a55-11eb-9fb8-d18059fef331.png)

**Comment by Alecto** [comment]
6 не исправлено, проверьте при потере фокуса

**Comment by mamamarina** [comment]
https://github.com/mamamarina/grid-template.git
https://mamamarina.github.io/grid-template/

**Comment by Alecto** [comment]
хорошо, работа принята.

пт, 4 груд. 2020 о 11:44 Maryna Tuboleva <notifications@github.com> пише:

> https://github.com/mamamarina/grid-template.git
> https://mamamarina.github.io/grid-template/
>
